exclude: '(\.eggs|\.git|\.hg|\.mypy_cache|\.pytest_cache|\.tox|\.venv|venv|.env|env|\.vscode|static|media/|deployments|scripts|requirements|.*/templates|.*/migrations)'
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.3.2
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
