version: "3"

volumes:
  static_volume:
  media_volume:
  certs:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: name_django
    restart: always
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
      - static_volume:/home/app/web/src/static
      - media_volume:/home/app/web/src/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: name_postgres
    restart: always
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: name_nginx
    restart: always
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/src/static
      - media_volume:/home/app/web/src/media
      - certs:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django

  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: name_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: celery -A config worker -l info
    container_name: name_celery
    restart: always
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: celery -A config beat -l info
    container_name: name_celery_beat
    restart: always
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - redis
      - postgres
